"https://devis.programisto.fr":
    type: upstream
    upstream: "devis-rapide:http"

"http://devis.programisto.fr":
  type: redirect
  to: "https://devis.programisto.fr"

"https://www.devis.programisto.fr":
  type: redirect
  to: "https://devis.programisto.fr"

"http://www.devis.programisto.fr":
  type: redirect
  to: "https://devis.programisto.fr"
